name: Validate SDM schemas using Felis with Extra Checks

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run on"
        required: true
        default: "main"

jobs:
  validate-extra-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Python and install dependencies
        uses: ./.github/actions/setup-test-environment

      - name: Validate YAML files with extra checks
        run: |
          felis validate \
            --check-description \
            --check-redundant-datatypes \
            --check-tap-table-indexes \
            --check-tap-principal \
            ./yml/*.yaml
